#include <iostream>
    using namespace std;
    int main () {
        int a = 10;
        float b = 11;
         float hasil ;
        hasil = a + b;
        cout << a <<"+"<< + b << "=" << hasil << endl ;
        hasil = a - b;
        cout << a << "-" << - b << "=" << hasil << endl;
        hasil = a * b;
        cout << a << "*" << b << "=" << hasil << endl;
        hasil = a / b;
        cout << a << "/" <<  b << "=" << hasil << endl;
        return 0;
    }